import type { WisdomQuote } from '../../src/wisdom/payload.js'

/**
 * The quotes this app ships with.
 *
 * They are the answer to the one question a signage app must never fail: what is
 * on the screen when nothing has gone right? A player that has never once reached
 * the backend — freshly flashed, hung on a wall, plugged into a network that is
 * down — still has a snapshot of nothing, and a `server` app with no payload has
 * nothing to render. Every other app in this repo accepts that and shows a
 * "Loading…" line. A quote app can do better: a quote from 180 AD does not go
 * stale, so we simply carry a few.
 *
 * Used ONLY as a last resort — when the payload is missing or empty. The moment
 * the connector succeeds, live quotes replace these. They also carry no source
 * credit, because no third party served them.
 *
 * What these are, stated honestly: short, widely-published aphorisms, each one
 * attributed to its author on screen. Many are old enough to be plainly out of
 * copyright (Aurelius, Seneca, Lao Tzu, Franklin); some are twentieth-century and
 * are not — they are here as brief attributed quotations, which is the ordinary
 * and expected use of a quotation. If we ever want this list to be strictly
 * public-domain-by-age, the cut is mechanical: drop every author who died within
 * the last ~95 years. Keep entries SHORT and ALWAYS attributed either way.
 */
export const FALLBACK_QUOTES: WisdomQuote[] = [
  { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'Marcus Aurelius' },
  { text: 'The happiness of your life depends upon the quality of your thoughts.', author: 'Marcus Aurelius' },
  { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'Marcus Aurelius' },
  { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'Marcus Aurelius' },
  { text: 'If it is not right, do not do it; if it is not true, do not say it.', author: 'Marcus Aurelius' },
  { text: 'We suffer more often in imagination than in reality.', author: 'Seneca' },
  { text: 'Luck is what happens when preparation meets opportunity.', author: 'Seneca' },
  { text: 'It is not that we have a short time to live, but that we waste a lot of it.', author: 'Seneca' },
  { text: 'Difficulties strengthen the mind, as labour does the body.', author: 'Seneca' },
  { text: 'Every new beginning comes from some other beginning’s end.', author: 'Seneca' },
  { text: 'No man is free who is not master of himself.', author: 'Epictetus' },
  { text: 'It is impossible for a man to learn what he thinks he already knows.', author: 'Epictetus' },
  { text: 'First say to yourself what you would be; and then do what you have to do.', author: 'Epictetus' },
  { text: 'Wealth consists not in having great possessions, but in having few wants.', author: 'Epictetus' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'I know that I know nothing.', author: 'Socrates' },
  { text: 'The secret of change is to focus all of your energy not on fighting the old, but on building the new.', author: 'Socrates' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act but a habit.', author: 'Aristotle' },
  { text: 'Knowing yourself is the beginning of all wisdom.', author: 'Aristotle' },
  { text: 'The energy of the mind is the essence of life.', author: 'Aristotle' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'The beginning is the most important part of the work.', author: 'Plato' },
  { text: 'Be kind, for everyone you meet is fighting a harder battle.', author: 'Plato' },
  { text: 'Courage is knowing what not to fear.', author: 'Plato' },
  { text: 'A journey of a thousand miles begins with a single step.', author: 'Lao Tzu' },
  { text: 'When I let go of what I am, I become what I might be.', author: 'Lao Tzu' },
  { text: 'Nature does not hurry, yet everything is accomplished.', author: 'Lao Tzu' },
  { text: 'Mastering others is strength. Mastering yourself is true power.', author: 'Lao Tzu' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'Confucius' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Confucius' },
  { text: 'Real knowledge is to know the extent of one’s ignorance.', author: 'Confucius' },
  { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius' },
  { text: 'Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.', author: 'Goethe' },
  { text: 'Knowing is not enough; we must apply. Willing is not enough; we must do.', author: 'Goethe' },
  { text: 'Doubt can only be removed by action.', author: 'Goethe' },
  { text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'Do not go where the path may lead, go instead where there is no path and leave a trail.', author: 'Ralph Waldo Emerson' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Nothing great was ever achieved without enthusiasm.', author: 'Ralph Waldo Emerson' },
  { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
  { text: 'It is not enough to be busy. The question is: what are we busy about?', author: 'Henry David Thoreau' },
  { text: 'The price of anything is the amount of life you exchange for it.', author: 'Henry David Thoreau' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'The two most important days in your life are the day you are born and the day you find out why.', author: 'Mark Twain' },
  { text: 'Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did.', author: 'Mark Twain' },
  { text: 'Kindness is the language which the deaf can hear and the blind can see.', author: 'Mark Twain' },
  { text: 'Continuous effort — not strength or intelligence — is the key to unlocking our potential.', author: 'Winston Churchill' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.', author: 'Winston Churchill' },
  { text: 'If you are going through hell, keep going.', author: 'Winston Churchill' },
  { text: 'Nothing in life is to be feared, it is only to be understood.', author: 'Marie Curie' },
  { text: 'Be less curious about people and more curious about ideas.', author: 'Marie Curie' },
  { text: 'One never notices what has been done; one can only see what remains to be done.', author: 'Marie Curie' },
  { text: 'Imagination is more important than knowledge.', author: 'Albert Einstein' },
  { text: 'Life is like riding a bicycle. To keep your balance you must keep moving.', author: 'Albert Einstein' },
  { text: 'Try not to become a man of success, but rather try to become a man of value.', author: 'Albert Einstein' },
  { text: 'In the middle of difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'The present is theirs; the future, for which I really worked, is mine.', author: 'Nikola Tesla' },
  { text: 'If you want to find the secrets of the universe, think in terms of energy, frequency and vibration.', author: 'Nikola Tesla' },
  { text: 'I do not think there is any thrill that can go through the human heart like that felt by the inventor.', author: 'Nikola Tesla' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'I have not failed. I’ve just found 10,000 ways that won’t work.', author: 'Thomas Edison' },
  { text: 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.', author: 'Thomas Edison' },
  { text: 'Whether you think you can or you think you can’t, you’re right.', author: 'Henry Ford' },
  { text: 'Coming together is a beginning; keeping together is progress; working together is success.', author: 'Henry Ford' },
  { text: 'Obstacles are those frightful things you see when you take your eyes off your goal.', author: 'Henry Ford' },
  { text: 'Quality means doing it right when no one is looking.', author: 'Henry Ford' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', author: 'Benjamin Franklin' },
  { text: 'An investment in knowledge pays the best interest.', author: 'Benjamin Franklin' },
  { text: 'Either write something worth reading or do something worth writing.', author: 'Benjamin Franklin' },
  { text: 'Lost time is never found again.', author: 'Benjamin Franklin' },
  { text: 'It is never too late to be what you might have been.', author: 'George Eliot' },
  { text: 'What we call the beginning is often the end. And to make an end is to make a beginning.', author: 'T. S. Eliot' },
  { text: 'Only those who will risk going too far can possibly find out how far one can go.', author: 'T. S. Eliot' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'In three words I can sum up everything I’ve learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.', author: 'Robert Frost' },
  { text: 'Not all those who wander are lost.', author: 'J. R. R. Tolkien' },
  { text: 'Little by little, one travels far.', author: 'J. R. R. Tolkien' },
  { text: 'We are all in the gutter, but some of us are looking at the stars.', author: 'Oscar Wilde' },
  { text: 'Be yourself; everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde' },
  { text: 'Experience is simply the name we give our mistakes.', author: 'Oscar Wilde' },
  { text: 'There is no greater agony than bearing an untold story inside you.', author: 'Maya Angelou' },
  { text: 'Do the best you can until you know better. Then when you know better, do better.', author: 'Maya Angelou' },
  { text: 'The only limit to our realization of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Happiness lies in the joy of achievement and the thrill of creative effort.', author: 'Franklin D. Roosevelt' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'Believe you can and you’re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Nothing worth having comes easy.', author: 'Theodore Roosevelt' },
  { text: 'Keep your eyes on the stars, and your feet on the ground.', author: 'Theodore Roosevelt' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'Great minds discuss ideas; average minds discuss events; small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'Be the change that you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Darkness cannot drive out darkness; only light can do that.', author: 'Martin Luther King Jr.' },
  { text: 'The time is always right to do what is right.', author: 'Martin Luther King Jr.' },
  { text: 'Faith is taking the first step even when you don’t see the whole staircase.', author: 'Martin Luther King Jr.' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'A winner is a dreamer who never gives up.', author: 'Nelson Mandela' },
  { text: 'The best way to predict the future is to create it.', author: 'Abraham Lincoln' },
  { text: 'Whatever you are, be a good one.', author: 'Abraham Lincoln' },
  { text: 'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.', author: 'Abraham Lincoln' },
  { text: 'I am a slow walker, but I never walk back.', author: 'Abraham Lincoln' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'You must have chaos within you to give birth to a dancing star.', author: 'Friedrich Nietzsche' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanese proverb' },
  { text: 'The best time to plant a tree was twenty years ago. The second best time is now.', author: 'Chinese proverb' },
  { text: 'A smooth sea never made a skilled sailor.', author: 'Proverb' },
  { text: 'Slow and steady wins the race.', author: 'Aesop' },
  { text: 'No act of kindness, no matter how small, is ever wasted.', author: 'Aesop' },
  { text: 'After all, tomorrow is another day.', author: 'Margaret Mitchell' },
  { text: 'Whatever you do, do it well.', author: 'Walt Disney' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'All our dreams can come true, if we have the courage to pursue them.', author: 'Walt Disney' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Learning never exhausts the mind.', author: 'Leonardo da Vinci' },
  { text: 'Time stays long enough for anyone who will use it.', author: 'Leonardo da Vinci' },
  { text: 'I have been impressed with the urgency of doing. Knowing is not enough; we must apply.', author: 'Leonardo da Vinci' },
  { text: 'Every block of stone has a statue inside it, and it is the task of the sculptor to discover it.', author: 'Michelangelo' },
  { text: 'The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low and achieving our mark.', author: 'Michelangelo' },
  { text: 'I am still learning.', author: 'Michelangelo' },
  { text: 'Ambition is the path to success. Persistence is the vehicle you arrive in.', author: 'Bill Bradley' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'The greatest weapon against stress is our ability to choose one thought over another.', author: 'William James' },
  { text: 'Nothing is impossible; the word itself says “I’m possible”.', author: 'Audrey Hepburn' },
  { text: 'The most wasted of days is one without laughter.', author: 'E. E. Cummings' },
  { text: 'It takes courage to grow up and become who you really are.', author: 'E. E. Cummings' },
  { text: 'What you do speaks so loudly that I cannot hear what you say.', author: 'Ralph Waldo Emerson' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'There is no path to happiness: happiness is the path.', author: 'Buddha' },
  { text: 'Better than a thousand hollow words is one word that brings peace.', author: 'Buddha' },
  { text: 'Peace comes from within. Do not seek it without.', author: 'Buddha' },
  { text: 'Three things cannot be long hidden: the sun, the moon, and the truth.', author: 'Buddha' },
  { text: 'What we think, we become.', author: 'Buddha' },
  { text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', author: 'Rumi' },
  { text: 'The wound is the place where the light enters you.', author: 'Rumi' },
  { text: 'What you seek is seeking you.', author: 'Rumi' },
  { text: 'Set your life on fire. Seek those who fan your flames.', author: 'Rumi' },
  { text: 'Everything you can imagine is real.', author: 'Pablo Picasso' },
  { text: 'Action is the foundational key to all success.', author: 'Pablo Picasso' },
  { text: 'Inspiration exists, but it has to find you working.', author: 'Pablo Picasso' },
  { text: 'The meaning of life is to find your gift. The purpose of life is to give it away.', author: 'Pablo Picasso' },
]
