/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    solutions: Solution;
    'app-pages': AppPage;
    redirects: Redirect;
    categories: Category;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    'app-pages': AppPagesSelect<false> | AppPagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('sr' | 'en') | ('sr' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'sr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * URL segment, per language — /blog/<slug> and /sr/blog/<slug>. Write it in the language of the post. Changing it requires a redirect.
   */
  slug: string;
  excerpt?: string | null;
  /**
   * Search-result title. Falls back to the post title and should lead with the term people search for. Aim for under ~60 characters.
   */
  metaTitle?: string | null;
  /**
   * Falls back to the excerpt. Aim for 140–160 characters.
   */
  metaDescription?: string | null;
  coverImage?: (string | null) | Media;
  category?: (string | null) | Category;
  author?: (string | null) | User;
  publishedAt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional concise conclusions for readers. Do not use these to repeat the introduction.
   */
  keyTakeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary sources and evidence used for claims in this language version.
   */
  references?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Define the search need before writing. Indexable pages should have a distinct query, job-to-be-done and promise.
   */
  intent?: {
    /**
     * The main query this page should answer. Use one natural-language query, not a list of keywords.
     */
    primaryQuery?: string | null;
    intentType?: ('informational' | 'commercial-investigation' | 'transactional' | 'navigational') | null;
    /**
     * Who is searching, including their role or level of experience.
     */
    audience?: string | null;
    /**
     * What the visitor needs to decide, understand or complete.
     */
    jobToBeDone?: string | null;
    /**
     * The value this page provides that no sibling Blog, Solution or App page provides.
     */
    uniquePromise?: string | null;
    /**
     * Nearby queries this page deliberately does not target. Use this to prevent cannibalisation.
     */
    notTargeting?: string | null;
  };
  seoWorkflowVersion?: number | null;
  /**
   * Search and social metadata for this language. Keep canonical override empty unless consolidating a known duplicate.
   */
  seo?: {
    /**
     * Search-result title. Aim for under ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search-result description. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Allow this language version to be indexed once its content is complete and distinct.
     */
    indexable?: boolean | null;
    /**
     * Advanced: an absolute canonical URL for deliberate consolidation. Normally leave empty for a self-canonical.
     */
    canonicalOverride?: string | null;
  };
  /**
   * This language version is complete, reviewed and safe to expose on its public URL.
   */
  localeReady?: boolean | null;
  /**
   * When this language version was last checked for accuracy.
   */
  lastReviewedAt?: string | null;
  /**
   * Editor responsible for the latest review of this language version.
   */
  reviewedBy?: (string | null) | User;
  /**
   * Editorially selected guides that deepen or support this page.
   */
  relatedPosts?: (string | Post)[] | null;
  /**
   * Industries for which this content is directly useful.
   */
  relatedSolutions?: (string | Solution)[] | null;
  /**
   * Apps that directly help the reader complete the job described on this page.
   */
  relatedApps?: (string | AppPage)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  /**
   * Shown under the image in article bodies.
   */
  caption?: string | null;
  /**
   * Photographer name.
   */
  credit?: string | null;
  /**
   * Photographer profile URL.
   */
  creditUrl?: string | null;
  /**
   * Original photo page.
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: string;
  name: string;
  /**
   * URL segment, per language — /solutions/<slug> and /sr/resenja/<slug>. Changing it requires a redirect.
   */
  slug: string;
  /**
   * Ascending. Ties fall back to name.
   */
  order?: number | null;
  /**
   * Resolved to a Lucide icon in src/lib/solution-icons.ts.
   */
  icon:
    | 'utensils'
    | 'shopping-bag'
    | 'building'
    | 'heart-pulse'
    | 'hotel'
    | 'dumbbell'
    | 'graduation-cap'
    | 'landmark'
    | 'pill'
    | 'car'
    | 'key-round'
    | 'scissors'
    | 'croissant'
    | 'clapperboard'
    | 'bus'
    | 'factory'
    | 'laptop'
    | 'paw-print'
    | 'shopping-cart'
    | 'party-popper';
  /**
   * Two sentences. Shown on the overview card — make it earn the click.
   */
  tagline: string;
  title: string;
  subtitle?: string | null;
  /**
   * Falls back to the page title. Aim for under ~60 characters.
   */
  metaTitle?: string | null;
  /**
   * Falls back to the subtitle. Aim for 140–160 characters.
   */
  metaDescription?: string | null;
  /**
   * Two or three paragraphs (blank line between them) on why a screen belongs in this industry — the context before the scenarios. This is most of what makes the page rank; without it the page is a list.
   */
  intro?: string | null;
  /**
   * Aim for five or six. Three reads as a stub.
   */
  scenarios?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * A clearly labelled illustrative workflow or calculation. Never present an invented example as a customer result, and do not promise an outcome that has not been measured.
   */
  proof?: {
    title?: string | null;
    body?: string | null;
  };
  /**
   * Legacy comma-separated app keys. Existing pages still read this field; migrate values to Related apps before retiring it.
   */
  recommendedApps?: string | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Eight to ten. Write them as they get asked on a sales call, and answer at a length worth reading — a one-line answer is the shape nothing ever cites. Avoid reusing an answer across industries: twenty pages carrying the same sentence is what thin content looks like to a crawler.
   */
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Define the search need before writing. Indexable pages should have a distinct query, job-to-be-done and promise.
   */
  intent?: {
    /**
     * The main query this page should answer. Use one natural-language query, not a list of keywords.
     */
    primaryQuery?: string | null;
    intentType?: ('informational' | 'commercial-investigation' | 'transactional' | 'navigational') | null;
    /**
     * Who is searching, including their role or level of experience.
     */
    audience?: string | null;
    /**
     * What the visitor needs to decide, understand or complete.
     */
    jobToBeDone?: string | null;
    /**
     * The value this page provides that no sibling Blog, Solution or App page provides.
     */
    uniquePromise?: string | null;
    /**
     * Nearby queries this page deliberately does not target. Use this to prevent cannibalisation.
     */
    notTargeting?: string | null;
  };
  seoWorkflowVersion?: number | null;
  /**
   * Search and social metadata for this language. Keep canonical override empty unless consolidating a known duplicate.
   */
  seo?: {
    /**
     * Search-result title. Aim for under ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search-result description. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Allow this language version to be indexed once its content is complete and distinct.
     */
    indexable?: boolean | null;
    /**
     * Advanced: an absolute canonical URL for deliberate consolidation. Normally leave empty for a self-canonical.
     */
    canonicalOverride?: string | null;
  };
  /**
   * This language version is complete, reviewed and safe to expose on its public URL.
   */
  localeReady?: boolean | null;
  /**
   * When this language version was last checked for accuracy.
   */
  lastReviewedAt?: string | null;
  /**
   * Editor responsible for the latest review of this language version.
   */
  reviewedBy?: (string | null) | User;
  /**
   * Editorially selected guides that deepen or support this page.
   */
  relatedPosts?: (string | Post)[] | null;
  /**
   * Industries for which this content is directly useful.
   */
  relatedSolutions?: (string | Solution)[] | null;
  /**
   * Structured replacement for the legacy Recommended apps keys. Select the app pages that genuinely support this industry.
   */
  relatedApps?: (string | AppPage)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-pages".
 */
export interface AppPage {
  id: string;
  /**
   * Stable key from @signagewall/apps. It joins this page to product behaviour and must not change when the SEO slug changes.
   */
  appKey: string;
  /**
   * Ascending order on curated app lists.
   */
  order?: number | null;
  name: string;
  /**
   * Localised marketing URL segment. It is independent from appKey so a technical key such as "gcal" can use "google-calendar".
   */
  slug: string;
  /**
   * Page heading. Falls back to the app name.
   */
  heroTitle?: string | null;
  /**
   * A concise statement of the problem this app solves and who it solves it for.
   */
  summary?: string | null;
  /**
   * Unique narrative content. Explain the workflow and value instead of paraphrasing the product manifest.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Concrete jobs and settings for this app. These should not repeat the generic feature list.
   */
  useCases?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  setupSteps?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * User-facing account, data, network and playback constraints. Keep these factual and consistent with the technical manifest.
   */
  requirements?: {
    account?: string | null;
    dataSource?: string | null;
    network?: string | null;
    refreshBehavior?: string | null;
    offlineBehavior?: string | null;
    limitations?: string | null;
  };
  /**
   * Real interface or output images. Avoid decorative mockups that imply unsupported behaviour.
   */
  screenshots?: (string | Media)[] | null;
  faq?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Define the search need before writing. Indexable pages should have a distinct query, job-to-be-done and promise.
   */
  intent?: {
    /**
     * The main query this page should answer. Use one natural-language query, not a list of keywords.
     */
    primaryQuery?: string | null;
    intentType?: ('informational' | 'commercial-investigation' | 'transactional' | 'navigational') | null;
    /**
     * Who is searching, including their role or level of experience.
     */
    audience?: string | null;
    /**
     * What the visitor needs to decide, understand or complete.
     */
    jobToBeDone?: string | null;
    /**
     * The value this page provides that no sibling Blog, Solution or App page provides.
     */
    uniquePromise?: string | null;
    /**
     * Nearby queries this page deliberately does not target. Use this to prevent cannibalisation.
     */
    notTargeting?: string | null;
  };
  /**
   * Search and social metadata for this language. Keep canonical override empty unless consolidating a known duplicate.
   */
  seo?: {
    /**
     * Search-result title. Aim for under ~60 characters.
     */
    metaTitle?: string | null;
    /**
     * Search-result description. Aim for 140–160 characters.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the meta title.
     */
    ogTitle?: string | null;
    /**
     * Falls back to the meta description.
     */
    ogDescription?: string | null;
    ogImage?: (string | null) | Media;
    /**
     * Allow this language version to be indexed once its content is complete and distinct.
     */
    indexable?: boolean | null;
    /**
     * Advanced: an absolute canonical URL for deliberate consolidation. Normally leave empty for a self-canonical.
     */
    canonicalOverride?: string | null;
  };
  /**
   * This language version is complete, reviewed and safe to expose on its public URL.
   */
  localeReady?: boolean | null;
  /**
   * When this language version was last checked for accuracy.
   */
  lastReviewedAt?: string | null;
  /**
   * Editor responsible for the latest review of this language version.
   */
  reviewedBy?: (string | null) | User;
  /**
   * Editorially selected guides that deepen or support this page.
   */
  relatedPosts?: (string | Post)[] | null;
  /**
   * Industries for which this content is directly useful.
   */
  relatedSolutions?: (string | Solution)[] | null;
  /**
   * Alternative or complementary apps. Do not select this page itself and do not create a generic app carousel.
   */
  relatedApps?: (string | AppPage)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Old path including any locale prefix, without domain, query or fragment.
   */
  fromPath: string;
  /**
   * Canonical destination path including any locale prefix.
   */
  toPath: string;
  statusCode: '308' | '307';
  active?: boolean | null;
  /**
   * Pass the incoming query string to the destination.
   */
  preserveQuery?: boolean | null;
  /**
   * Why this redirect exists, for example a slug change or merged thin page.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'solutions';
        value: string | Solution;
      } | null)
    | ({
        relationTo: 'app-pages';
        value: string | AppPage;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  metaTitle?: T;
  metaDescription?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  content?: T;
  keyTakeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  references?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  intent?:
    | T
    | {
        primaryQuery?: T;
        intentType?: T;
        audience?: T;
        jobToBeDone?: T;
        uniquePromise?: T;
        notTargeting?: T;
      };
  seoWorkflowVersion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        indexable?: T;
        canonicalOverride?: T;
      };
  localeReady?: T;
  lastReviewedAt?: T;
  reviewedBy?: T;
  relatedPosts?: T;
  relatedSolutions?: T;
  relatedApps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  order?: T;
  icon?: T;
  tagline?: T;
  title?: T;
  subtitle?: T;
  metaTitle?: T;
  metaDescription?: T;
  intro?: T;
  scenarios?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  proof?:
    | T
    | {
        title?: T;
        body?: T;
      };
  recommendedApps?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  intent?:
    | T
    | {
        primaryQuery?: T;
        intentType?: T;
        audience?: T;
        jobToBeDone?: T;
        uniquePromise?: T;
        notTargeting?: T;
      };
  seoWorkflowVersion?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        indexable?: T;
        canonicalOverride?: T;
      };
  localeReady?: T;
  lastReviewedAt?: T;
  reviewedBy?: T;
  relatedPosts?: T;
  relatedSolutions?: T;
  relatedApps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-pages_select".
 */
export interface AppPagesSelect<T extends boolean = true> {
  appKey?: T;
  order?: T;
  name?: T;
  slug?: T;
  heroTitle?: T;
  summary?: T;
  content?: T;
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  setupSteps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        account?: T;
        dataSource?: T;
        network?: T;
        refreshBehavior?: T;
        offlineBehavior?: T;
        limitations?: T;
      };
  screenshots?: T;
  faq?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  intent?:
    | T
    | {
        primaryQuery?: T;
        intentType?: T;
        audience?: T;
        jobToBeDone?: T;
        uniquePromise?: T;
        notTargeting?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        indexable?: T;
        canonicalOverride?: T;
      };
  localeReady?: T;
  lastReviewedAt?: T;
  reviewedBy?: T;
  relatedPosts?: T;
  relatedSolutions?: T;
  relatedApps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  fromPath?: T;
  toPath?: T;
  statusCode?: T;
  active?: T;
  preserveQuery?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  creditUrl?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}